import { createTheme, MantineProvider } from '@mantine/core';
import '@mantine/core/styles.css';
import { Notifications } from '@mantine/notifications';
import '@mantine/notifications/styles.css';
import './global.css';
import Nav from './ui/Nav';

export const metadata = {
  title: 'Welcome to juice-wallpaper',
  description: 'Generated by create-nx-workspace',
};

const theme = createTheme({
  /** Put your mantine theme override here */
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <MantineProvider theme={theme}>
          <Nav />
          <main>{children}</main>
          <Notifications position="bottom-center" limit={3} />
        </MantineProvider>
      </body>
    </html>
  );
}
