import './global.css';
import '@mantine/core/styles.css';
import { createTheme, MantineProvider } from '@mantine/core';

export const metadata = {
  title: 'Welcome to juice-wallpaper',
  description: 'Generated by create-nx-workspace',
};

const theme = createTheme({
  /** Put your mantine theme override here */
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <MantineProvider theme={theme}>{children}</MantineProvider>
      </body>
    </html>
  );
}
